version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-107-21-201-210.compute-1.amazonaws.com
            port: '5432'
            database: dbbk67jr23nd19
            user: lyksczizncrpml
            password: 2f584c8f161d19abf2422a23e003e5c1d1c67a94beb8292710f76a1f4f9e5570
            migrations: true
            rawAccess: true
            ssl: true 